Repository prateekc231/hacktofest, pull requests merged in 2022-10, with the labels that each got.

#9 Double Hashing
  Double Hashing
Labels: hacktoberfest-accepted

#10 added one file
  Ladder/22_PresentFromLenna.cpp
Labels: enhancement, hacktoberfest-accepted

#11 added one file
  Ladder/23_Jeff and Digits.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 added one file
  Ladder/24_SlightlyDecreasingPermutations.cpp
Labels: enhancement, hacktoberfest-accepted

#13 added one file
  Ladder/25_Sale.cpp
Labels: enhancement, hacktoberfest-accepted

#14 commit ad 26 fancy fence
  Ladder/26_FancyFence.cpp
Labels: hacktoberfest-accepted

#15 added new file
  Ladder/27_Dragons.cpp
Labels: hacktoberfest-accepted

#16 added new file
  Ladder/28_TheNoOfPositions.cpp
Labels: enhancement, hacktoberfest-accepted

#17 added new file
  Ladder/29_Translation.cpp
Labels: enhancement, hacktoberfest-accepted

#18 added new file
  Ladder/30_WizardsandDemonstration.cpp
Labels: enhancement, hacktoberfest-accepted
